In [1]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr=np.arange(4,10)
print(arr)

[4 5 6 7 8 9]


In [3]:
arr=np.arange(2,10,2)
print(arr)

[2 4 6 8]


In [4]:
arr_1D=np.array([1,2,3,4,5])
print(arr_1D)
print(arr_1D[2])

[1 2 3 4 5]
3


In [7]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D.shape)

(3, 3)
